# Writes virusTraceVersion.h with the commit each trace was generated from.
#
# Run as a build step rather than at configure time: the stamp has to describe
# the binary that wrote the trace, and a configure-time capture goes stale the
# moment you commit and rebuild without reconfiguring. A trace whose provenance
# is quietly wrong is worse than one with none.

function(git_describe _dir _outVar)
	set(_sha "unknown")
	execute_process(
		COMMAND git -C "${_dir}" rev-parse --short=12 HEAD
		OUTPUT_VARIABLE _sha OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
	if(NOT _sha)
		set(_sha "unknown")
	endif()

	# analysis tools get run from dirty trees constantly, and "commit X plus
	# uncommitted changes" is the honest answer in that case
	execute_process(
		COMMAND git -C "${_dir}" status --porcelain --untracked-files=no
		OUTPUT_VARIABLE _dirty OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
	if(_dirty)
		set(_sha "${_sha}-dirty")
	endif()

	set(${_outVar} "${_sha}" PARENT_SCOPE)
endfunction()

git_describe("${GEARMULATOR_DIR}" GEARMULATOR_SHA)
git_describe("${GEARMULATOR_DIR}/source/dsp56300" DSP56300_SHA)

set(_content "#pragma once\n")
string(APPEND _content "// Generated by version.cmake at build time. Do not edit.\n")
string(APPEND _content "#define VIRUSTRACE_GEARMULATOR_SHA \"${GEARMULATOR_SHA}\"\n")
string(APPEND _content "#define VIRUSTRACE_DSP56300_SHA \"${DSP56300_SHA}\"\n")

# only rewrite on change, so an unchanged commit does not force a rebuild
set(_existing "")
if(EXISTS "${OUTPUT_FILE}")
	file(READ "${OUTPUT_FILE}" _existing)
endif()
if(NOT _existing STREQUAL _content)
	file(WRITE "${OUTPUT_FILE}" "${_content}")
endif()
